// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
namespace BroadCapture.Models
{
    //You can get Utilities package via nuget : Install-Package Deszolate.Utilities.Lite
    //[Utilities.Attributes.SQL.Table("Message")]
    public partial class Message
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public int? Type { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public bool IsSell { get; set; }
        public bool IsBuy { get; set; }
        public bool IsTrade { get; set; }
    }
}

