// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a ModelGenerator.
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using BroadCapture.Repositories.Based;
using BroadCapture.Models;
namespace BroadCapture.Repositories
{
	///<summary>
	/// Data contractor for Message
	///</summary>
	public partial class MessageRepository : Repository<Message>
	{
		private readonly Service Service;
		public MessageRepository(Service service) : base(service.Connector)
		{
			this.Service = service;
		}
	}
}

